### ISSUE TITLE
Enhancement: Disable link for Info Boxes

### ISSUE THREAD

**Issue by webmaster-cob** [kadencewp/kadence-blocks#100]
It'd be great to have the option for the link to be disabled for Info Boxes. Either a toggle or by entering # in the URL value.

**Comment by kadencewp** [comment]
Hey,
 You can change the link in the settings to only be for the "learn more" text then turn off the learn more text. That would get you the same thing.

Ben

**Comment by webmaster-cob** [comment]
Ah - perfect! Thanks for the quick reply.
