### ISSUE TITLE
Feature Request: svg icon upload

### ISSUE THREAD

**Issue by chaselifetech** [kadencewp/kadence-blocks#101]
Great plugin, request svg icon upload using standard method, not via iconmoon

**Comment by kadencewp** [comment]
Hey, 

You can add an image widget and upload an SVG and add it to your page. If you just want to put an svg into your site that would work.

Or if you want to add it inline can use an html block to drop an svg icon code into your page. 

Making icons work inside of react is a much more complex process. Uploading a file doesn't give you the kind of control that the icon block needs to output inline and you can't output as an image and define colors, etc.

Iconmoon is free and very simple to use, can you tell me what you've not liked about it, perhaps I can make that process easier for you.

Ben

**Comment by chaselifetech** [comment]
Hi Ben,
Thank you for the quick response.
That’s fine, I have done a few things the more technical way, just thought it would be easier a straight upload. I’ve added icons to the footer using the svg tag in a html widget so it’s not a big deal.

Cheers

David
Sent from my iPhone

On 20 Aug 2020, at 22:58, Benjamin Ritner <notifications@github.com> wrote:

﻿

Hey,

You can add an image widget and upload an SVG and add it to your page. If you just want to put an svg into your site that would work.

Or if you want to add it inline can use an html block to drop an svg icon code into your page.

Making icons work inside of react is a much more complex process. Uploading a file doesn't give you the kind of control that the icon block needs to output inline and you can't output as an image and define colors, etc.

Iconmoon is free and very simple to use, can you tell me what you've not liked about it, perhaps I can make that process easier for you.

Ben
