### ISSUE TITLE
Add the svg support fix to Kadence-blocks or as plugin

### ISSUE THREAD

**Issue by GrimLink** [kadencewp/kadence-blocks#103]
As state in issue #82 the svg icons are broken for users that are not super admins on multisite Wordpress installation.

The provide fix is great.
But does not work in wordpress 5.4.
And probably also in 5.5.

Any chance the fix can be added here to the kadence-blocks?
Or offered as a separate plugin?

Until Wordpress offers this option instead 😒

**Comment by kadencewp** [comment]
Hey, I'm not having any issue on 5.4 or 5.5? What plugin are you using? 

Ben

**Comment by GrimLink** [comment]
Hi Ben

Weird?
Have your tried doing this on Multisite Wordpress 5.4 or higher with a normal admin or editor role user?

As for the plugin this is what you shared in issue #82 
-> http://download.kadencethemes.com/kadence-blocks-author-svg-support.zip
This module trows an error if installed in a multi site.

**Comment by kadencewp** [comment]
I usually use this on multisite, running it now without issues: https://wordpress.org/plugins/unfiltered-mu/

Just tested with the Kadence Plugin on a multisite and didn't have any issue. 

What error are you seeing?

Ben

**Comment by GrimLink** [comment]
@kadencewp I can't reproduce the error at the moment.
Since I did not had time to access this specific project at the time.
Since it is also work related.
And I somehow can't reproduce this locally.

I am not experiencing this with the Kadence Block or with [unfiltered-mu](https://wordpress.org/plugins/unfiltered-mu/)
I am experiencing this bug with http://download.kadencethemes.com/kadence-blocks-author-svg-support.zip which you shared in the issue #82 

Also not a fan of plugins that have not been updated for more than 1 year.
And [unfiltered-mu](https://wordpress.org/plugins/unfiltered-mu/) has not been updated for more than 2 years!

**Comment by kadencewp** [comment]
So just to I'm clear you can't recreate any but with the Kadence Blocks Author SVG support plugin right?

> Also not a fan of plugins that have not been updated for more than 1 year.
I understand that however in a situation like Unfiltered MU it's a super simple plugin, just a few lines of code, if you are worried about the plugin being outdated you can just use a snippet plugin or child theme and add in the few lines of code yourself :)

**Comment by GrimLink** [comment]
> So just to I'm clear you can't recreate any but with the Kadence Blocks Author SVG support plugin right?

Yes.
I was hoping you could add this plugin as actual plugin, you can download from Wordpress or via github.
Or part of the Kadence blocks it self.
And also update the code of `Kadence Blocks Author SVG` to work with the latest Wordpress versions.

> I understand that however in a situation like Unfiltered MU it's a super simple plugin, just a few lines of code, if you are worried about the plugin being outdated you can just use a snippet plugin or child theme and add in the few lines of code yourself :)

You are right I should ask for some time to update the code, for work.
So I don't have to use outdated code 😉

Please let me know if you are going to do it.
If not, you can close this this issue.

**Comment by kadencewp** [comment]
At this time there are no plans to import that plugin into Kadence Blocks. It's not a great solution, it's simply a hack that can work most of the time. For some SVGS it still will not work because of how kses breaks svgs with x1 and y1 attributes.

There are tickets open in core that would provide a better fix so we are hoping core deals with the problem as it's not specific to our plugin.

Ben

**Comment by GrimLink** [comment]
Thanks Ben for your reply.
I have worked around this issue for now.
And will wait for the core fix.
So closing this issue 😉
