### ISSUE TITLE
Feature Request: Post Grid number of items setting and filtering results

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#113]
It would be great to have the Number of Items setting in combination with the filter results taxonomy settings return the number of items for the "All" view and the same number of items under each filtered option (assuming there were enough in each category of the taxonomy to fill each view). Currently, the behavior seems to be returning the Number of Items count in the "All" view and then filtering those results in each filtered view.

**Comment by kadencewp** [comment]
A "filter" is not a new query, it's simply hiding and showing based on what you click and whats on the page. It should not be used as a menu if you have a lot of posts. If you have a ton of posts that you want to show you should use a menu and link to different pages.

Ben

**Comment by SJNBham** [comment]
Thanks for the reply, Ben. I understand it's not a bug now that you've explained what the expected behavior is by design.
