### ISSUE TITLE
Unexpected scroll to the top of the page with accordion

### ISSUE THREAD

**Issue by jchwenger** [kadencewp/kadence-blocks#126]
Hi there,

I'm encountering something odd on [this page](https://artasperto.ch/#artistes): the accordion works perfectly (on [this page](https://artasperto.ch/artistes/) for instance) with Firefox 85.0.1, but for some reason on the home page whenever one clicks on any of the panes the page scrolls back to the top. I wonder if that might not have something to do with the accordion being embedded, or something clashing with other elements ? I'm sorry to write for such a detail, but so far I couldn't find any solution to this (everything fine with Chrome).

Many thanks for reading!
Best,
J.

**Comment by kadencewp** [comment]
Hey,
 That wouldn't be coming from a script from blocks. I suggest you go into troubleshooting mode and figure out if your theme or what other plugin might be causing that.

https://kadence-theme.com/knowledge-base/troubleshooting/temporarily-deactivating-plugins/

Ben

**Comment by jchwenger** [comment]
Thanks so much for this, will do! Jeremie
