### ISSUE TITLE
Bug: Advanced Gallery - Fluid Carousel: Lightbox not working on last left image

### ISSUE THREAD

**Issue by JoachimVeulemans** [kadencewp/kadence-blocks#127]
I have a problem with the Advanced Gallery - Fluid Carousel. I have added a list of images and set them all to Link to: Media File & Link Triggers: Lightbox.

When clicking the middle image (first in the list), lightbox is working as expected. This continues for the next images. The left image on load (last image in last) doesn't open the lightbox when clicked. It opens the media file without lightbox. The same issue is present on the demo website https://www.kadenceblocks.com/custom-blocks/advanced-gallery/ under 'Fluid Carousel – with Mayfair filter'.

**Comment by kadencewp** [comment]
Hey, thanks for posting, someone else posted about this week as well. I have an update coming on in the next day that will resolve this.

Ben

**Comment by JoachimVeulemans** [comment]
Fixed now, thanks!
