### ISSUE TITLE
Update to version 1.10.6 causes an bug in Gutenslider v4.5.0

### ISSUE THREAD

**Issue by desouza10** [kadencewp/kadence-blocks#130]
Hi team, 

I had a little problem with my Gutenslider (v4.5.0) plugin of WordPress, when I did the update to 1.10.6 Kadence Blocks version. 
At the moment, I'm using the 1.9.18 Kadence Blocks version, and this is the stable version to my website in operation with Gutenslider (updated version). 
When I disabled the Kandece Blocks plugin, my Gutenslider plugin works normally.

Please, do you can help me with this case?

**Wordpress version:** 5.7
**Kadence Blocks stable version:** 1.9.18
**Kadence Blocks update caused:** 1.10.6 
**Gutenslider version:** 4.5.0

**Comment by kadencewp** [comment]
It looks like the Gutenslider is setting the editor device to undefined when the block initializes. I don't know why a plugin would do this. I'll add some checks to prevent an error on the side of Kadence if the device size in the editor is undefined.

Ben
