### ISSUE TITLE
Feature: Collapse Order

### ISSUE THREAD

**Issue by kingpangilinan25** [kadencewp/kadence-blocks#131]
Perhaps it will be cool if Column Vertical Gutter/Gap and "Collapse Order" option are also available in tablet. 
Currently I only see it for mobile view

**Comment by kadencewp** [comment]
The mobile would affect tablet assuming you are collapsing the columns on tablet. are you wanting to have a different order for tablet and mobile?

**Comment by kingpangilinan25** [comment]
Ohhh that's how it works... Thank You for letting me know, I'm still new to the blocks ( Sorry )..
Though it will be great if we can setup them separately too... ;)
