### ISSUE TITLE
Question: Is this the only repo for kadence-blocks?

### ISSUE THREAD

**Issue by ribaricplusplus** [kadencewp/kadence-blocks#133]
Hello, thank you for making Kadence Blocks!

I just wanted to know if this is the only repository or if there is a different repository where actual development happens. Actually, given there's a premium version, there is certainly a private repo, but I was wondering if there is a repository that has more developer tooling, like tests and so forth.

I'm asking because I want to look around the code and maybe even help out as I use this plugin and find things to fix, so if there's a separate repo with better tooling, that would at least be interesting information even if I cannot access it.

Thank you for your time

**Comment by superewald** [comment]
Maybe a bit late but I think discussion in #165 is what you were looking for and #190 should solve this.
The current build system is using CodeKit which is paid software (and mac only), the PR (#190) will move to gulp.

**Comment by ribaricplusplus** [comment]
Thank you for the update. Closing the issue.
