### ISSUE TITLE
Section/Column z-index control set to 0 rendered in editor content, nothing applied on front-end

### ISSUE THREAD

**Issue by vena** [kadencewp/kadence-blocks#135]
In a Row Layout's Column block, under Advanced, setting the Z-Index Control to 0 causes a "0" to be rendered in the editor above the column's content container. On the front-end, the 0 z-index is not applied, leaving it at 1 from the default row.style stylesheet.

<img width="1296" alt="Screen Shot 2021-05-03 at 11 40 16 AM" src="https://user-images.githubusercontent.com/867733/116898432-5cb2cb00-ac04-11eb-942b-e3b48e0cd409.png">

Special request on this one - would the option of setting z-index to "auto" be possible, either explicitly or as a consequence of entering 0? Even if all columns are set to the same numerical z-index, any numerical z-index (including 0) on columns seems to create a stacking order from its order in the markup. 

My use case is a row of columns, each containing a "card" block. When you hover over each card, the hovered card changes its z-index to 2 and transforms scale, so it would overlap the cards on either side of it. When all columns are set to the same numerical z-index, the implicit stacking order always puts later columns and their content on top of the column before it, making the desired effect impossible.

**Comment by kadencewp** [comment]
Thanks for reporting the issue about 0 showing in the backend. I can certainly make 0 output "auto" instead of how it currently is where 0 doesn't output anything. I'll put this in today's update.
