### ISSUE TITLE
[Bug] Unable to remove link from link setting in Advanced Heading & Advanced Button

### ISSUE THREAD

**Issue by oakesjosh** [kadencewp/kadence-blocks#143]
Attempting to erase or clear the link in the link settings results in it being repopulated with the link.

A separate customer is also reporting that an "x" to delete the current link used to appear next to the pencil icon and is requesting that that makes a comeback.
![Screen Shot 2021-06-23 at 11 33 50 AM](https://user-images.githubusercontent.com/61174/123134928-e6b62d80-d416-11eb-8103-4744dc7d032e.png)

Example
https://share.getcloudapp.com/Z4uKrqoK

**Comment by kadencewp** [comment]
Resolved 2.0.11
