### ISSUE TITLE
[Bug] Row Block issues with parallax effect and force no image on mobile

### ISSUE THREAD

**Issue by oakesjosh** [kadencewp/kadence-blocks#148]
There appears to be to be a front end and back end display issue when using the following

**To Replicate**
Add a background image to a Row Block Layout
Set the Background image display option to Parallax
Set the Mobile Background to Force no image for mobile

**In editor**: The background image still appears in the mobile view

**In front end**: When resizing the page from a desktop or tablet resolution to a mobile resolution the background image is not hidden.  If the page is loaded using a mobile resolution the image is hidden as expected

**Comment by kadencewp** [comment]
Resolved 2.0.11
