### ISSUE TITLE
[Bug] In row Layout block: setting overlay opacity to 0 results in unexpected value

### ISSUE THREAD

**Issue by oakesjosh** [kadencewp/kadence-blocks#149]
**To Recreate**
Create a row layout block with a background image
Set a custom background overlay for mobile
Adjust overlay opacity slider to 0

The opacity parameter will be set to 1.0 on the image resulting in it being shown instead of hidden

When setting overlay opacity to 0 on an _overlay color_, the opacity is set to 0.3 or 30%

**Comment by kadencewp** [comment]
Resolved 2.0.11
