### ISSUE TITLE
Kadence blocks broken in 2.1.4?

### ISSUE THREAD

**Issue by xayberoptix** [kadencewp/kadence-blocks#151]
It seems that Kadence blocks is no longer working after updating to 2.1.4.  All I am seeing when I edit a page that used a Kadence block is a button that suggests to "Convert to HTML."  Anyone having the same issue?

**Comment by kadencewp** [comment]
Hi, what version of WordPress are you using?

**Comment by xayberoptix** [comment]
5.8

**Comment by kadencewp** [comment]
I can't recreate that. Can you tell me what is in your error log?

**Comment by xayberoptix** [comment]
I reverted back to 2.1.3 and now everything works as it did before.

**Comment by kadencewp** [comment]
Interesting? Had you tried deactivating other plugins? I can't recreate an issue like this. I don't know how to fix if I can't recreate

**Comment by xayberoptix** [comment]
It could be possible that there's a conflict with another plugin.  Let's wait and see whether anyone else is running into the same issue.

**Comment by kadencewp** [comment]
I'm going to close this, you are welcome to reopen if you want to provide more information.
