### ISSUE TITLE
Build block styles wihtout codekit

### ISSUE THREAD

**Issue by superewald** [kadencewp/kadence-blocks#165]
### summary
Hi, I am trying to add a new feature (indented icon-lists). It works so far in the editor but the styles are not applied at the frontend.

### details
I modified the `src/blocks/icon-list` in order to allow indention of entries. Styles and scripts are both modified.

Running `npm run build` does compile scripts and the main stylesheet (`dist/build/blocks.css`) but it doesn't compile frontend styles to `dist/blocks/icon-list.style.build.css` and thus, changes to `src/blocks/icon-list/style.css` are not reflected at frontend! .

**How do I compile the frontend stylesheets (`dist/blocks/[name].style.build.css`) for the blocks ?**
The only guess I have is that codekit is used to compile such styles (which would be very bad for me as I don't own a license for that).

**Comment by oakesjosh** [comment]
Hello! We are using codekit for compiling many of the styles. The codekit config is in the repo and they do have a free trial, but moving away from codekit is on our to-do list.

**Comment by superewald** [comment]
> Hello! We are using codekit for compiling many of the styles. The codekit config is in the repo and they do have a free trial, but moving away from codekit is on our to-do list.

Thanks for the quick reply!  Two things:

1. I opened a PR for a simple feature which needs to recompile those block styles. Would it be sufficient to include every change except the recompiled block styles and outsourcing the compilation to someone who owns codekit ?

2. I may be able to help with refactoring to webpack. The only change required is to compile all block styles with webpack and save them to `dist/blocks/[name].style.build.css`, right ? I've already done that while fiddling with this plugin and could create a PR for it.

**Comment by oakesjosh** [comment]
1. Yeah that works! Thank you for contributing

2. That would be great! That's the main thing codekit does, but there's a few others. If you just want to make a PR for what you have now that'd be great starting point too.

Here's the list I've come up with
`/src/blocks/*/style.scss` to `/dist/blocks/*.style.build.css`
`/dist/assets/css/src/*.scss` to `/dist/assets/css/*.css`
`/dist/assets/js/src/*.js` to `/dist/assets/js/*-min.js` 
`/dist/assets/js/kb-form.js` to `/dist/assets/js/kb-form-min.js`
`/dist/settings/dashboard.scss` to `/dist/settings/styles.css`
`/dist/vendor/kt-blocks-slick.scss` to `/dist/vendor/kt-blocks-slick.css`
`/dist/kt-accordion.js` to `/dist/kt-accordion-min.js`
`/dist/kt-tabs.js` to `/dist/kt-tabs-min.js`
`/dist/magnific.scss` to `/dist/magnific.css`

**Comment by superewald** [comment]
> 1. Yeah that works! Thank you for contributing
> 2. That would be great! That's the main thing codekit does, but there's a few others. If you just want to make a PR for what you have now that'd be great starting point too.
> 
> Here's the list I've come up with `/src/blocks/*/style.scss` to `/dist/blocks/*.style.build.css` `/dist/assets/css/src/*.scss` to `/dist/assets/css/*.css` `/dist/assets/js/src/*.js` to `/dist/assets/js/*-min.js` `/dist/assets/js/kb-form.js` to `/dist/assets/js/kb-form-min.js` `/dist/settings/dashboard.scss` to `/dist/settings/styles.css` `/dist/vendor/kt-blocks-slick.scss` to `/dist/vendor/kt-blocks-slick.css` `/dist/kt-accordion.js` to `/dist/kt-accordion-min.js` `/dist/kt-tabs.js` to `/dist/kt-tabs-min.js` `/dist/magnific.scss` to `/dist/magnific.css`

Well the way I did it might be not applicable to all of this files, the structure raises a few questions:
1. is there a specific reason *source* files are located in the `dist` directory ? I might be missing something but I think they should be moved to `src/assets` or sth like that (which would make bundling them easier)
2. do you want those files to be bundled up or still reside in their dedicated files ? As far as I understood everything except `src/blocks/*` and `dist/settings/*` are loaded by default so we could bundle those together and define a seperate entry point for the blocks and settings page.

My proposal would be:

- move source files from `dist` to `src`
- introduce 2 new webpack entries:
    - `shared`: contains shared js/scss needed on every page
    - `admin`: contains js/scss dedicated to the admin/settings page
- include the `/src/blocks/*` into the main entry point

I think that would be the webpack'ish approach as it doesn't really support compiling individual files. Another option is to use gulp/grunt but that might be overkill here.

**Comment by superewald** [comment]
As I would love to extend this plugin even further it would be nice to have some updates on this issue so I can build it myself without codekit and not being forced to use my own fork. 

I already tried implementing the proposal above and with some minor tweaks it does work but leads to some little bugs that needs to be resolved. However, before I clean up that approach and create PR I'd love to know if you're ok with that :)

**Comment by kadencewp** [comment]
Hey,
 There are no files needed on every page. Everything is in pieces because it's only loaded when needed and only the parts that are needed are loaded. Moving the uncompressed addon javascript files to the src folder is fine but they need to still all be compressed separately. 

I hope that clarifies. Happy to look at any PR.
