### ISSUE TITLE
[Improvement] Don't generate .rtl styles unless the "is_rtl" check is passed

### ISSUE THREAD

**Issue by rinart73** [kadencewp/kadence-blocks#215]
When the plugin generates CSS it adds RTL styles. However they're basically unused CSS for left to right locales.
```php
$css .= '.rtl .wp-block-kadence-tabs .kt-tabs-id' . $unique_id . ' > .kt-tabs-title-list li .kt-tab-title {';
  $css .= 'margin-right:0px;';
  $css .= 'margin-left:' . $attr['gutter'][0] . 'px;';
$css .= '}';
```
Wordpress has a function that allows to determine if current locale is RTL: `is_rtl()`. I propose to use it during CSS generation to not add RTL styles unless needed.

**Comment by oakesjosh** [comment]
Thanks for reporting this. The dynamically generated RTL css is now wrapped in this check
