### ISSUE TITLE
CSS not reducing after deactivating certain modules

### ISSUE THREAD

**Issue by lydenyardley** [kadencewp/kadence-blocks#53]
Hello,

I'm interested in switching from 'Ultimate Addons for Gutenberg' to Kadence Blocks, but one of my primary reasons for doing so isn't working quite as expected:

There are a bunch of blocks I won't be using, so I deactivated them, cleared caches, and checked the network tab of Chrome Dev Tools to check the CSS and JS weight >>> **no change**.

Is the idea that only the code for the necessary blocks is compiled? That's what I was hoping, as otherwise, I'm likely to be using ~10% of the code I'm forcing users to download. My focus, asking this question, is on speed.

**Comment by kadencethemes** [comment]
Hey,
 This is in the works, part of my planned improvements. 

Ben

**Comment by kadencethemes** [comment]
The JS only loads when needed already on the front end.

**Comment by lydenyardley** [comment]
I noticed that actually between setting testimonials between carousel and grid. GREAT work there!

**Comment by kadencewp** [comment]
Just cleaning up some of these tickets, this has been implemented.
Ben
