### ISSUE TITLE
Outputting unnecessary empty CSS declarations

### ISSUE THREAD

**Issue by lydenyardley** [kadencewp/kadence-blocks#54]
Does your plugin need to create all this unnecessary CSS code for every selector on every block in your library? This particular output is for `.kt-testimonial-style-bubble .kt-testimonial-text-wrap`
```
element.style {
    border-color: rgba(238, 238, 238, 1);
    border-radius: px;
    border-top-width: px;
    border-right-width: px;
    border-bottom-width: px;
    border-left-width: px;
    padding: undefinedpx undefinedpx undefinedpx undefinedpx;
}
```
 It'd be preferable to not load anything if the fields in the block editor settings are cleared. Can that be instigated?

**Comment by kadencethemes** [comment]
Hey,
 I'm looking into this, Are you seeing this on the front end?

Ben

**Comment by lydenyardley** [comment]
Yes - here's a screenshot: 
![Screenshot 2019-08-06 at 17 47 39](https://user-images.githubusercontent.com/2838799/62559157-54ccc800-b872-11e9-97f0-2be677f51563.png)

**Comment by kadencethemes** [comment]
Thanks, I will fix that.

Ben

**Comment by lydenyardley** [comment]
Hi Ben,

Did you manage to solve this one?

Lyden

**Comment by kadencewp** [comment]
yes that should have been fixed a while ago. are you still seeing it somewhere?

Ben

**Comment by lydenyardley** [comment]
Hi @kadencewp 

Yes, it appears that you did resolve that particular case, but in testing just now, I notice there are still empty strings being output when the setting are cleared from the block editor. See screenshot:

![Demonstrating expertise _ Lyden Yardley (staging1 yardley me) - 2019 10 03-11_12_11](https://user-images.githubusercontent.com/2838799/66118793-2566dd00-e5cf-11e9-9958-5bbc6f1cd5cc.jpg)

**Comment by kadencewp** [comment]
I'll take a look.
