### ISSUE TITLE
Support Font Awesome WordPress Plugin integration

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#57]
Font Awesome provides a WordPress plugin to manage easy access to both their free and pro sets of icons. It would be great to have the Kadence plugin updated to integrate with the FA plugin so more icons are available in Kadence blocks. Here's some info listed by the FA plugin related to integration with other plugins (while Kadence Blocks plugin is active). Note that Kadence isn't listed as an registered/active client:

**Client Requirements**
We don't detect any other active clients (like themes or plugins) that have registered requirements for Font Awesome.

Contact the developer for the unregistered client and ask them to consider updating their code to register with this Font Awesome Official plugin. Let them know they can reach us at hello@fontawesome.com

The current selection of 300 icons is great, but not enough for large sites that use icons extensively. 

Thanks for considering this enhancement ;)

PS(as a temporary workaround, is there a way to manually load in more icons to the source of where Kadence blocks are pulling from?)

**Comment by kadencethemes** [comment]
Hey,
 This plugin uses inline SVGs so it's not pulling in large icon fonts, it only adds the svg where it's used. You can install a plugin like this: https://wordpress.org/plugins/svg-support/ to add svg support to WordPress and upload any icon you want to use as an image.

I'll take a look at the font awesome plugin but last I looked it loads through an icon font, which is a different type of setup.

I'm surprised font awesome hasn't created an icon block if they have a plugin.

**Comment by SJNBham** [comment]
Might be worth reaching out to FA at hello@fontawesome.com as it sounds like they're happy to give insight to integration options. 

I'll look at the SVG angle also - thanks for the quick response ;)

**Comment by SJNBham** [comment]
There seems to be a reference to SVG support and a framework for it on the official plugin site:

https://wordpress.org/plugins/font-awesome

**Comment by SJNBham** [comment]
I tried using the Font Awesome SVG files and the Kadence image option. The block allows me to addit to a page, but the image/icon is cropped. When I try to reduce the size of the image, the outer border of the icon shirks with it. Hoping you see some potential in the updated SVG framework from FA. 

Thanks for taking the time to look in to this.

**Comment by kadencewp** [comment]
Hey,
 What Kadence Image option are you referring to specifically?

Can you send a screen shot?

**Comment by SJNBham** [comment]
To reproduce:

- Download Font Awesome and extract the SVG versions of the icons to a local computer
- Install an SVG WordPress plugin to allow them to be uploaded
- Add a Kadence Info Box block
- Expand the Media Settings section of the block properties
- Change Media Type to Image
- Choose the Media Library option in the block and and upload and select a Font Awesome SVG file
- Change the Max Image Width setting to 70px to match the default for other Info Box icons (the image is cropped.
- Try to reduce the Max Image Width so the image isn't cropped and it resize the whole Info Box icon down with it. 

When using the built in Kadence icons, the interior icons scale with the Icon Size setting. 

I can send a screenshot, but basically the experience is really poor. It doesn't scale, I'm guessing the color has to be manually set before uploading the SVG (no on-the-fly color changes), and there's no way for users to search by keyword to filter the icons (unless you count the Media Library which would require site admins to seed all the icons with metadata).

**Comment by SJNBham** [comment]
Any leads on the potential to link FA into this block? Wonder if the free version of Kadence blocks could have the 300 built-in icons and then the Pro version could have the option to link to the free and pro version of Font Awesome. Might be a good selling point for people to go premium with this plugin.

**Comment by kadencewp** [comment]
This is what I was wanting  to know "Kadence Info Box"

As long as you force your svg inline (part of some svg support plugins) then this plugin will set the color.

can you send the svg file you were using, I can't recreate a crop and I can scale.

**Comment by SJNBham** [comment]
Ah - I get a bit further with that. I didn't understand I needed the SVG plugin to render in-line. I had just been using Safe SVG so I could upload the SVG files. I was trying to avoid using the SVG Support plugin because it hasn't been updated in a while and is only tested to 5.1.1.  Once I installed SVG Support, turned on the Enable Advanced Mode, and selected Force Inline SVG in the plugin settings, the icon no longer gets cropped and sizes correctly with the Max Image Width. It's also getting the color applied properly, although it isn't reflected in the editor. I'm still seeing some border distortion based on the shape of the FA icon (e.g. elongated vertically) and the padding between the icon and border varies depending on the icon. See the following page for an example.

[https://cityofbellingh.wpengine.com/acorn](https://cityofbellingh.wpengine.com/acorn)

The Aquatic Center icon has a smaller padding between the border and icon
The Jobs icon is elongated vertically
Both are set to "70" for Max Image Size to match the default Icon Size of 70 for this block

Thanks for working with me on this. It would be great to find a workaround for now. Still really hopeful for a full Font Awesome integration at some point :)

**Comment by kadencewp** [comment]
I agree a better way to integrate any icons of any source it ideal, it's tricker than you think because I want the output to be an SVG and not an icon font which is tricky to render in react in the editor and then output to the front end. But it's something I am working on possible solutions.

The issue on that test site you sent is the Kadence Block tries to respect image ratios. Since the svgs are not all square this is why you get the odd shape. Adding this css could resolve that:


```
.kb-info-box-image-type-svg .kt-info-svg-image {
    width: 70px !important;
    height: 70px !important;
}

.kb-info-box-image-type-svg.kadence-info-box-image-intrisic {
    padding-bottom: 100% !important;
}

```

**Comment by SJNBham** [comment]
Thanks for the CSS tweak - that definitely helped. I also noticed if I open the FA SVGs in Adobe Illustrator, rotate them so the widest tips of the icons are aligned with the middle of each side of the artboard, and then scale the paths down to be within the artboard, then rotated it back to its original orientation, the resulting SVG provides the "equal" padding compared to a "circular" shaped icon. See the following page for an example. The two alarm clocks - 1st is original from FA and the second was modified using the Illustrator method above. Not sure which one of the two looks better, but that's a way to get "exact" padding between the icon and border:

[https://cityofbellingh.wpengine.com/acorn](https://cityofbellingh.wpengine.com/acorn)

It will be next to impossible to get our content editors to add this code and adjust it based on the size of the icons they want to use on a particular page. But at least I have a temporary workaround for a set size of icon.

I found the following that looked interesting: [https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core](https://fontawesome.com/how-to-use/on-the-web/advanced/svg-javascript-core)

While it would be cool to support any icon set, Font Awesome is pretty widely used and could be an interim solution if the more comprehensive "all icon" option is further out of reach.

Again - really appreciate you working with me on this.

**Comment by kadencewp** [comment]
Hey,
 Yeah I've seen where they require javascript to render the icon after loading. It's a way but not idea for a block plugin. I'm considering some options.

**Comment by KonradDeskiewicz** [comment]
Any update on that one? I'm facing the same problem. Can add each icon as SVG (tons of effort) but then there is no "text color" for media in the info block, so I end up with no styling options for SVG icon added this way.

**Comment by kadencewp** [comment]
With Kadence Blocks Pro we've implemented a way to add custom icons https://www.kadenceblocks.com/docs/custom-icons/
