### ISSUE TITLE
Feature Request: number of columns for mobile, tablet, and desktop

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#58]
Currently columns in the posts/grid block appear to automatically collapse base on mobile, tablet, and desktop. However, there may be times when you'd like control the number of columns for each break point.  For example, you may want 3 columns on desktop and a single column on tablet and mobile to make it easier to read than a 2 column layout on tablet. The [Ultimate Addons for Gutenberg](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/) offers this type of configuration.
<img width="185" alt="2019-08-19 15_39_26-Edit Page ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/11393597/63304408-bee46480-c297-11e9-9fed-68190958f45f.png">

Thanks for considering this request.

**Comment by SJNBham** [comment]
I didn't see the linked and individual options at first. Looks like this is already baked in. Thanks

**Comment by kadencewp** [comment]
Hey, you can already define if columns should break down and how they should. There are layout options for tablet and mobile. 

<a href="https://imgbb.com/"><img src="https://i.ibb.co/hH18z4Q/Screen-Shot-2019-08-19-at-4-44-47-PM.png" alt="Screen-Shot-2019-08-19-at-4-44-47-PM" border="0"></a>

What about this request is different?

Ben

**Comment by SJNBham** [comment]
Just to clarify - I was referring to the Post Grid/Carousel block column layout vs. the Row Layout block column layout. But in any case, I found the settings by selecting the "Individual" vs. the "linked" option. I didn't see it at first because I was expecting the desktop/tablet/mobile icons like in the row layout block ;)   Thanks
<img width="196" alt="2019-08-19 16_27_00-Edit Page ‹ City of Bellingham — WordPress" src="https://user-images.githubusercontent.com/11393597/63306159-56e54c80-c29e-11e9-99d4-efd8dc030825.png">
