### ISSUE TITLE
Bug: Filter by Category overlaps other settings

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#59]
When using the Post Grid/Carousel block and selecting the "Filter by Category", the dropdown field background appears to be transparent. The Filter by Tag may have the same issue.

![image](https://user-images.githubusercontent.com/11393597/63629469-4b0fc800-c5c7-11e9-84fa-796441395021.png)

**Comment by kadencewp** [comment]
i'll see if I can overide their css.

**Comment by kadencewp** [comment]
This is resolved as of the latest update.
