### ISSUE TITLE
Feature request: larger gutter option at 125px or ability to set a custom gutter width

### ISSUE THREAD

**Issue by afridley** [kadencewp/kadence-blocks#61]
I would like to see a gutter width option at 125px or ability, preferably, the ability to set a custom gutter width that would either show up as on option or just convert the gutter width option to text input.

**Comment by kadencewp** [comment]
Thanks for your post. Currently, gutters are set with a class, perhaps I'll look into switching that into an inline css that would allow for custom sizes. What you can do currently is define padding with your columns.
