### ISSUE TITLE
Feature request: Text color setting on Column block settings

### ISSUE THREAD

**Issue by rchipka** [kadencewp/kadence-blocks#62]
As per #5, we can now set text color for an entire Row Layout.

This is useful in situations where we have rows with background colors that require the appropriate contrast on all text within the block.

Sometimes we have a scenario where a particular column in a multi-column layout has a different background color in order to call out some bit of information.

In these scenarios, it'd be nice to have a text color setting available on the column itself, especially since background color settings are already provided.

It's currently possible to work around this limitation by nesting another Row Layout inside the column and setting the background/text color on that instead.

While this solution is adequate, it's not something that would be immediately recognized by the user.

**Comment by kadencewp** [comment]
I'll include this in the next update.

**Comment by kadencewp** [comment]
This was added
