### ISSUE TITLE
Resizing Spacer block

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#63]
I have a Spacer/Divider block above an Advanced button block and try to resize the Spacer using the bottom, middle resizing node. The insert new block dot and the spacer resize node are so close together it makes it difficult to choose the resizing node. 
![resize-spacer](https://user-images.githubusercontent.com/11393597/64055573-23c67700-cb42-11e9-9e92-d86a0ac8254e.gif)

**Comment by onuro** [comment]
Hey guys, just so you know:

That is a common Gutenberg issue, and is being revisited in the coming release.

**Comment by SJNBham** [comment]
It looks like this may have been solved by removing the option to resize the Kadence spacer block directly on the page. You can resize it by using the block properties panel. The Gutenberg spacer still has the option to resize on the page.
