### ISSUE TITLE
Null margins are not displayed

### ISSUE THREAD

**Issue by deodat** [kadencewp/kadence-blocks#68]
Hello,

For the Advanced Heading, I've noticed that a value of 0 for a margin (and maybe a padding, I didn't try) isn't displayed in the generated style of the block. 
It's a problem because it can be helpful to override the inherited value of the stylesheet. 

Regards,

David

**Comment by kadencewp** [comment]
Thanks for posting. You make a great point, I'll update this in the next version.

Ben

**Comment by kadencewp** [comment]
This is resolved in the latest update.
