### ISSUE TITLE
Feature Request: Image Overlay without a link

### ISSUE THREAD

**Issue by NRDay** [kadencewp/kadence-blocks#71]
An option to remove the link from the Image Overlay block would be great.

It's a great alternative to the standard Cover Image block, much more versatile, but forcing the image to be a link makes it a bit restrictive.

I could simply be that if there is no link in the link field then the image won't be wrapped in a an <a href> .

**Comment by kadencewp** [comment]
Thanks for the feature request. I've added it to my list to work on.

**Comment by kadencewp** [comment]
Closing this, the feature was added :)

**Comment by andreas-wpk** [comment]
Nice! Thank you so much :)
