### ISSUE TITLE
Kadence Block crashing after WP update?

### ISSUE THREAD

**Issue by Jorgexyx** [kadencewp/kadence-blocks#73]
I can no longer use Kadence Block anymore on WP 5.3.

The blocks build crashes when loading a new/edit page and does not allow me to add or edit my current Kadence Blocks

Error in console.
`Uncaught SyntaxError: Unexpected end of input blocks.build.js?ver=1.7.6:1 `

I have tried reinstalling Kadence but that did not fix the issue

**Comment by kadencewp** [comment]
Hey,
 I'm not aware of anyone else having this issue. I also can't recreate. Can you tell me what other plugins you have installed?

**Comment by Jorgexyx** [comment]
Thanks for the quick response! It does seem to only affect the current site im on as other sites do no exhibit the crash. 
Other plugins are
   - Woocommerce
   - ACF
   - Gravity Forms
   - Jetpack
   - Mailchimp
   - Custom In Built Plugin( I disbaled this already to check if our custom plugin broke kadence but did not resolve the issue)

**Comment by Jorgexyx** [comment]
It appears this seems to be a chrome bug? Switching over to Safari resolves the issue

**Comment by kadencewp** [comment]
Hmm strange, I'm in chrome right now, new version? Or a cached file?
