### ISSUE TITLE
Row Layout: Tablet padding issues

### ISSUE THREAD

**Issue by vwern** [kadencewp/kadence-blocks#74]
Hi,

When trying to set the tablet padding for the Row Layout block to 0, the padding will be set to blank if i set any other direction to any value which causes it to inherit the desktop padding.

**Comment by vwern** [comment]
It seems that for both desktop & mobile the RangeControl component is used but for tablet the MeasurementControls component is used.

**Comment by kadencewp** [comment]
Hey,
 This was fixed a little while ago. Tablet padding can be 0. What version of the plugin are you using?

**Comment by vwern** [comment]
I was using 1.7.6 and now i updated to 1.7.7 but no change.

**Comment by kadencewp** [comment]
Perhaps I am misunderstanding what is happening. Would it be possible for you to send a screenshot showing your padding settings?

Ben

**Comment by vwern** [comment]
![kt-issue](https://user-images.githubusercontent.com/58163371/69700273-b8fdeb00-10f2-11ea-8cb1-5a287d9c8683.gif)

I made a gif so you can actually see what happens.

**Comment by kadencewp** [comment]
Thank you! I get it now, I'll try and get an update out today with a fix.

**Comment by vwern** [comment]
Any updates?

**Comment by kadencewp** [comment]
Sorry, that plugin update was pushed back. I'll make it happen today

**Comment by vwern** [comment]
Issue has been resolved, closing.
