### ISSUE TITLE
Request Feature: More font weight options

### ISSUE THREAD

**Issue by webmaster-cob** [kadencewp/kadence-blocks#76]
When selecting font weight in certain blocks, only Normal and Bold are options. It would be great to have additional options like:

100, 200, 300, 400 (Normal), 500, 600, 700 (Bold), 800, 900

or

Normal, Bold, 100, 200, 300, 400, 500, 600, 700, 800, 900

[https://www.w3schools.com/cssref/pr_font_weight.asp](https://www.w3schools.com/cssref/pr_font_weight.asp)

There may be other blocks where font weight is set, but one example is the Info Box.

Thanks for considering this enhancement.

**Comment by kadencewp** [comment]
Hey,
 The weights are updated once you select a font family, for example if you set the font family to Roboto then you would see the 6 options Roboto has, if you select a font that only has one option then you would just see the one option that font has.

Ben

**Comment by webmaster-cob** [comment]
Ah - I see. Because I'm allow the font to be inherited, the options for the weight aren't presented. If I select the same font for the block config as it's already inheriting from the site, then the additional font weight options appear. Thanks ;)
