### ISSUE TITLE
Feature Request: Max-width and Margins for Info Box container

### ISSUE THREAD

**Issue by webmaster-cob** [kadencewp/kadence-blocks#77]
I've looked for settings to restrict the width of an info box and also add margins (to the bottom) of a box. Would be great to have these options. An example use would be when you go from desktop (3 column row layout) to tablet (1 column row layout). Mobile's mostly fine because it roughly reigns in the width automatically.

**Comment by kadencewp** [comment]
Thanks for your post, I'll look to adding.

Ben

**Comment by vwern** [comment]
> I've looked for settings to restrict the width of an info box

Would be a really helpful feature.

**Comment by kadencewp** [comment]
Max width was added to the latest version :)

Ben

**Comment by webmaster-cob** [comment]
Thanks Ben
