### ISSUE TITLE
User role capabilities and access to Kadence settings

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#78]
I'm working on creating roles for our users on our site. When I grant the edit_pages capability using User Role Editor, the Kadence Blocks dashboard is made available to that user role. I'm trying to allow our authors the ability to maintain pages, but not monkey with the Kadence dashboard settings where they can deactivate blocks, etc. Would it be possible to have the Kadence Blocks plugin add a custom capability that can be assigned to a user role to control access to its dashboard? Or maybe tie access to the Kadence dashboard to the manage_options capability...

**Comment by kadencewp** [comment]
I'll add this filter to the next update: kadence_blocks_admin_settings_capability. You can filter on that and change to any capability

Ben

**Comment by webmaster-cob** [comment]
Thanks Ben

**Comment by webmaster-cob** [comment]
Do you have sample code to add to functions.php to use this filter? I'm still new to WordPress and adding filters. Maybe a snippet that limited this capability to the administrator role?

**Comment by kadencewp** [comment]
```
add_filter( 'kadence_blocks_admin_settings_capability', 'custom_blocks_settings_capability' );
function custom_blocks_settings_capability( $cap ) {
$cap = 'manage_options';
return $cap;
}
```

**Comment by kadencewp** [comment]
Let me know if that helps

**Comment by webmaster-cob** [comment]
Thanks Ben - that appears to have done the trick. And Happy New Year ;)
