### ISSUE TITLE
Feature Request: Media Files Block

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#80]
A block that would dynamically display the files of a Media category. Could be used for displaying monthly reports, games schedules, printable publications, etc. Some of the options could include showing Title linked to file, file size, file type, caption, and description. Presentation could be an indented list or bullet list.

**Comment by kadencewp** [comment]
Thanks for your comment, Media doesn't have categories by default in WordPress, there are lots of plugins that can add that but they all do it a little differently. What plugin do you use to add categories?

**Comment by SJNBham** [comment]
Currently using [JoomUnited's Media Folders](https://www.joomunited.com/wordpress-products/wp-media-folder) as it provides a familiar interface for our site editors. It leverages categories so it's compatible with a lot of other plugins that use categories for access, etc.

**Comment by kadencewp** [comment]
To me, a block like you are suggesting is something a plugin like JoomUnited's Media Folders should create, not Kadence Blocks. It doesn't really make sense for Kadence to create a block that only works with other plugins that create the functionality inside wordpress core.

**Comment by SJNBham** [comment]
You asked what we are using for media categories, but there are other popular plugins that create categories as well:

https://wordpress.org/plugins/enhanced-media-library/ (100K active installs)
https://wordpress.org/plugins/wp-media-library-categories/ (30K active installs)

JoomUnited is less likely to create a block for this as they have a separate product that does file management with its own dedicated block. We're not leveraging that because it pulls the media files out of the media library, so other plugins don't integrate as well.

I understand media categories aren't in CORE. If you're looking to limit Kadence Blocks to supporting only core functionality, then I understand. Just saw a business need that others might have as well and haven't found a good solution yet ;)

Thanks for considering this request.

**Comment by kadencewp** [comment]
My point is simply that it makes more sense (to me) for any of the plugins you posted to create this block.  I appreciate you posting the request.

Ben
