### ISSUE TITLE
Feature Request: Block access profiles

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#81]
I see you've started to add support for access to block settings: https://github.com/kadencewp/kadence-blocks/issues/4

It would be great to have a higher-level of block access control to show/hide blocks by user/role. JoomUnited's [Advanced Gutenberg](https://wordpress.org/plugins/advanced-gutenberg/) plugin is doing this (although it doesn't appear to support Kadence Blocks yet). There's also the [Disable Gutenberg Blocks](https://wordpress.org/plugins/disable-gutenberg-blocks/) plugin that will do this globally, but not by user/role and it hasn't been updated in almost a year.

While this does seem a bit out of scope for Kadence Blocks, it would match the JoomUnited's offering and we haven't found an easy stand-alone solution for managing block visibility by user/role.

**Comment by kadencewp** [comment]
Gutenberg core has built-in options to disable blocks. So you shouldn't need to use a plugin like "Disable Gutenberg Blocks" any more.

By user role creates some issues, for example, if you add a block into a page and then a user role that doesn't have access to that block edits that page they will break the page when they save because they don't have access to the block.

 I can see scenarios where you want to have certain users editing posts and others that edit pages and only allowing some blocks for posts but it's a pretty small use case. can you give me some real world examples of how you would want this to work?

**Comment by SJNBham** [comment]
Our emphasis is more on ease of use than actually restricting editors from using certain blocks. It would allow us to reduce the clutter of blocks a user has to sift through. So just hiding them in the block selector vs. preventing them from editing a certain type of block would work. That might avoid the save issues you cited. 

Some use cases would include:

Consultant primarily maintains the site, but the client periodically updates simple text and headings. 
Certain user role only maintains events on the site and a very limited number of blocks are needed.
Certain user role only maintains project posts on the site and a very limited number of blocks are needed.

You make a good point about limiting blocks by post type/page. That would be an additional capability that would be useful in combination with by role. 

JoomUnited added this feature to their blocks plugin, so they must have seen some demand for it or likely wouldn't have put resources into developing it.

I only cited Disable Gutenberg Blocks because it would make sense to me for a 3rd party to develop a separate plugin to manage all 3rd party and CORE blocks instead of one particular block developer. But this was the closest plugin I could find and it appears to not be actively adding new features.

**Comment by kadencewp** [comment]
> So just hiding them in the block selector vs. preventing them from editing a certain type of block would work
I'll have to look through the code, I'm not sure that is possible, or at least a good idea. 

It's interesting, I've not had anyone tell me selecting a block is all that overwhelming but what you seem to be saying is that it is for clients when they click add block. How many block plugins are you using?

Ben

**Comment by SJNBham** [comment]
We have 118 blocks currently if you count Advanced Gutenberg blocks from JoomUnited. We're only installing those because of the block profile feature. Our preference is to point users to Kadence blocks instead when they need something other than the vanilla blocks from CORE. Technically we only have two actual block packages installed. But there are a bunch in CORE and a few added by sliders, photo galleries, event plugins, etc. Our current plan is to use the CORE block manager to hide a bunch of the embed blocks and either use the Advanced Gutenberg plugin or the built in Kadence block manager and call it good until we find a better option. It would be great to see something like User Role Editor add this as a feature since they've already delved in to metabox visibility. Not sure how the visibility/permissions/capabilities config works and if there's a clean way to manage all blocks similarly without having to take into account new blocks all the time. I reached out to JoomUnited because their plugin appear to have supported Kadence blocks in the block manager, but it's bugged now. They've promised to look in to it and likely will fix it. We understand you have limited dev resources and need to put them were they're most useful. Just looking to meet our business needs and noticed this as a gap in the WordPress ecosystem currently. Thanks for considering this.
