### ISSUE TITLE
Figure tag issue

### ISSUE THREAD

**Issue by SJNBham** [kadencewp/kadence-blocks#90]
Just an FYI in case others are running into this or someone's aware of a workaround:

[https://github.com/WordPress/gutenberg/issues/22715](https://github.com/WordPress/gutenberg/issues/22715)

Not sure it makes sense for Kadence to change the name of their class, but that could also possibly resolve the issue until Gutenberg is patched.

**Comment by SJNBham** [comment]
I saw some references to this possibly being the block editor adding figure tags around img tags instead of detecting a "figure" tag in the custom class name. Maybe the info box block could have figure tags around the image and then just give them a class/styling that "suppresses" them so they don't affect the code (e.g. aria hidden, display none, etc.). 

[https://stackoverflow.com/questions/54311510/gutenberg-block-validation-failed](https://stackoverflow.com/questions/54311510/gutenberg-block-validation-failed)

**Comment by SJNBham** [comment]
I tried adding an opening figure tag before the img tag and a closing figure tag after the img tag, but it still looks like WordPress is getting confused by the custom class name "kadence-info-box-image-inner-intrisic" and trying to detect figure from it.

![figure-tag-added](https://user-images.githubusercontent.com/11393597/83173214-8ba7ef00-a0cd-11ea-803b-14c9af4b41d3.png)

**Comment by kadencewp** [comment]
Can you paste the code you are trying to paste into the block editor here?

Ben

**Comment by SJNBham** [comment]
[https://github.com/WordPress/gutenberg/files/4697107/code-snippet.txt](https://github.com/WordPress/gutenberg/files/4697107/code-snippet.txt)

**Comment by kadencewp** [comment]
Do not click "resolve", click on the three dots and then "attempt block recovery"

See: https://www.kadenceblocks.com/docs/how-to-recover-a-broken-block/

**Comment by SJNBham** [comment]
That does appear to fix the block. However, that will involve manually touching every page of thousands for content migrations.

**Comment by kadencewp** [comment]
The code you have is broken, it's not current code that the info block puts out. Where are you getting it from, can you fix it at the source?

Ben

**Comment by SJNBham** [comment]
Yes - I can update the source code to whatever it needs to be. I was pulling it from a reusable block I created a couple of weeks ago I believe. I could try to use a new info box block and try to match the settings of the reusable block. I didn't realize the block code had changed recently. Do you think that would resolve the issue?

**Comment by kadencewp** [comment]
I don't see how that code was created a couple of weeks ago. For example the ID is `cob-info-block` and that isn't right. 

Either way just updating the source, or remaking it should resolve your issue.

**Comment by SJNBham** [comment]
OK - I'll try using a new block. It's possible the block was copied from another site at some point without me knowing.
