### ISSUE TITLE
Tabs block can have max 24 tabs

### ISSUE THREAD

**Issue by Tom-Woef** [kadencewp/kadence-blocks#95]
I used the kadence tabs block for dog names and each letter of the alfabet should be a new tab.
But i only can add content untill the letter X, from letter Y or 25the tab no option to add content in that tab.
Is this a know issue?
How to solve it?

**Comment by kadencewp** [comment]
Hey, can you tell me what version of Kadence Blocks you are using? Can you send a screen shot?

**Comment by Tom-Woef** [comment]
I'm using version 1.8.11
Screenshot of the problem i mean:
![image](https://user-images.githubusercontent.com/46788663/89631379-0006c780-d8a1-11ea-9804-53942ba24410.png)

**Comment by kadencewp** [comment]
Thanks for the screen shots, I believe I have this worked and will have a fix in the next version.
Ben
