### ISSUE TITLE
Icon list widget : The vertical alignment of the icon is always centered when the item is a link...

### ISSUE THREAD

**Issue by ylerjen** [kadencewp/kadence-blocks#99]
Hi there,
It seems there's a bug with the alignment of the icon in the "icon list widget".

## Steps to reproduce the bug

1. In a WP page, create a block of type "Icon List".
1. Create at list 1 item which has several lines.
1. Choose the vertical alignment = top
1. On the multi-line item, go to the item settings and add any url to the link field to transform the content of the list to a link.
1. Go to the page preview to see the bug (the editor view)

Once you preview the page, you'll notice the alignment is still centered.

It seems the alignement rules is set on the `li` tag, but once you add the link, a `<a>` tag is set as a child of the `<li>`, which breaks the `align-items` property placed on the `.kt-svg-icon-list-item-wrap`.

**Comment by kadencewp** [comment]
Thanks for sending, here is a quick fix, I'll add to the next version:

.wp-block-kadence-iconlist.kt-list-icon-aligntop ul.kt-svg-icon-list .kt-svg-icon-list-item-wrap a.kt-svg-icon-link {
    align-items: flex-start;
}
